### Go to hello world page
GET http://localhost:3000 HTTP/1.1

### Get all todos
GET http://localhost:3000/todos HTTP/1.1

### Get a specific todo
GET http://localhost:3000/todos/61b74511a247a4e80856d34b HTTP/1.1