### Go to hello world page
GET http://localhost:3000 HTTP/1.1

### Get all todos
GET http://localhost:3000/todos HTTP/1.1

### Get a specific todo
GET http://localhost:3000/todos/61b719e22f8b20c59e044378 HTTP/1.1